linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gosimple
    - typecheck

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-dirs:
    - vendor
