package coach

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shaiknoorullah/wtfrc/internal/kb"
)

// Interceptor generates per-tool wrapper config files that notify the coach
// daemon via FIFO write, then execute the original keybind action.
type Interceptor struct {
	fifoPath string
	configs  map[string]string // tool name -> generated config path
}

// NewInterceptor constructs an Interceptor, resolving per-tool config paths
// relative to the user's home directory.
func NewInterceptor(fifoPath string) *Interceptor {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		// Fall back to ~ if UserHomeDir fails (very unlikely).
		homeDir = "~"
	}

	join := func(rel string) string {
		return filepath.Join(homeDir, rel)
	}

	return &Interceptor{
		fifoPath: fifoPath,
		configs: map[string]string{
			"hyprland":    join(".config/hypr/wtfrc-intercept.conf"),
			"tmux":        join(".config/tmux/wtfrc-intercept.conf"),
			"kitty":       join(".config/kitty/wtfrc-intercept.conf"),
			"qutebrowser": join(".config/qutebrowser/wtfrc-intercept.py"),
			"yazi":        join(".config/yazi/wtfrc-intercept.toml"),
		},
	}
}

// SetConfigPath overrides the generated config path for a tool. Useful for
// testing without touching ~/.config/.
func (ic *Interceptor) SetConfigPath(tool, path string) {
	ic.configs[tool] = path
}

// ---------------------------------------------------------------------------
// Per-tool config generators
// ---------------------------------------------------------------------------

// generateHyprland produces a Hyprland keybind interceptor config.
// For each entry it emits a bind that writes to the FIFO then dispatches the
// original action.
func generateHyprland(entries []kb.KBEntry, fifoPath string) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by wtfrc coach. Do not edit.\n")
	for _, e := range entries {
		if e.RawBinding == nil || e.RawAction == nil {
			continue
		}
		binding := *e.RawBinding
		action := *e.RawAction
		fmt.Fprintf(&sb, "# Original: bind = %s, %s\n", binding, action)
		fmt.Fprintf(&sb,
			"bind = %s, exec, echo \"kb:hyprland:%s\" >> %s & hyprctl dispatch %s\n",
			binding, action, fifoPath, action,
		)
	}
	return sb.String()
}

// generateTmux produces a tmux interceptor config.
// Each entry wraps the original action with a run-shell to write to the FIFO.
func generateTmux(entries []kb.KBEntry, fifoPath string) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by wtfrc coach. Do not edit.\n")
	for _, e := range entries {
		if e.RawBinding == nil || e.RawAction == nil {
			continue
		}
		binding := *e.RawBinding
		action := *e.RawAction
		fmt.Fprintf(&sb, "# Original: %s %s\n", binding, action)
		fmt.Fprintf(&sb,
			"%s run-shell \"echo 'kb:tmux:%s' >> %s\" \\; %s\n",
			binding, action, fifoPath, action,
		)
	}
	return sb.String()
}

// generateKitty produces a kitty keybind interceptor config.
// Each entry uses the "combine" action to chain a background launch (FIFO
// write) with the original action.
func generateKitty(entries []kb.KBEntry, fifoPath string) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by wtfrc coach. Do not edit.\n")
	for _, e := range entries {
		if e.RawBinding == nil || e.RawAction == nil {
			continue
		}
		binding := *e.RawBinding
		action := *e.RawAction
		fmt.Fprintf(&sb, "# Original: map %s %s\n", binding, action)
		fmt.Fprintf(&sb,
			"map %s combine : launch --type=background sh -c 'echo kb:kitty:%s >> %s' : %s\n",
			binding, action, fifoPath, action,
		)
	}
	return sb.String()
}

// generateQutebrowser produces a qutebrowser Python interceptor config.
// Each entry uses config.bind with a spawn -d to write to the FIFO before
// executing the original action.
func generateQutebrowser(entries []kb.KBEntry, fifoPath string) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by wtfrc coach. Do not edit.\n")
	sb.WriteString("import os\n")
	fmt.Fprintf(&sb, "fifo = %q\n", fifoPath)
	for _, e := range entries {
		if e.RawBinding == nil || e.RawAction == nil {
			continue
		}
		binding := *e.RawBinding
		action := *e.RawAction
		fmt.Fprintf(&sb, "# Original: config.bind('%s', '%s')\n", binding, action)
		fmt.Fprintf(&sb,
			"config.bind('%s', 'spawn -d sh -c \"echo kb:qb:%s >> ' + fifo + '\" ;; %s')\n",
			binding, action, action,
		)
	}
	return sb.String()
}

// generateYazi produces a yazi TOML interceptor config.
// Each entry uses the prepend_keymap with a shell command that writes to the
// FIFO, followed by the original action.
func generateYazi(entries []kb.KBEntry, fifoPath string) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by wtfrc coach. Do not edit.\n")
	for _, e := range entries {
		if e.RawBinding == nil || e.RawAction == nil {
			continue
		}
		binding := *e.RawBinding
		action := *e.RawAction
		sb.WriteString("[[manager.prepend_keymap]]\n")
		fmt.Fprintf(&sb, "on = [%q]\n", binding)
		fmt.Fprintf(&sb,
			"run = ['shell \"echo kb:yazi:%s >> %s\" --confirm', %q]\n",
			action, fifoPath, action,
		)
	}
	return sb.String()
}

// ---------------------------------------------------------------------------
// Install / Remove / Regenerate
// ---------------------------------------------------------------------------

// Install generates and writes interceptor configs for all known tools.
// For each tool it queries the DB for keybind entries; if none are found an
// empty file is written (making any source/include line a no-op).
func (ic *Interceptor) Install(db *kb.DB) error {
	for tool, cfgPath := range ic.configs {
		entries, err := db.GetEntriesByToolAndType(tool, "keybind")
		if err != nil {
			return fmt.Errorf("interceptor Install: get entries for %s: %w", tool, err)
		}

		var content string
		if len(entries) > 0 {
			content = ic.generate(tool, entries)
		}

		if err := writeFileWithDirs(cfgPath, content); err != nil {
			return fmt.Errorf("interceptor Install: write %s: %w", cfgPath, err)
		}
	}
	return nil
}

// Remove writes empty files for all tool interceptor configs, making any
// source/include line a no-op without removing the file itself.
func (ic *Interceptor) Remove() error {
	for tool, cfgPath := range ic.configs {
		if err := writeFileWithDirs(cfgPath, ""); err != nil {
			return fmt.Errorf("interceptor Remove: write %s (%s): %w", cfgPath, tool, err)
		}
	}
	return nil
}

// Regenerate removes all interceptor configs then re-installs them from the DB.
func (ic *Interceptor) Regenerate(db *kb.DB) error {
	if err := ic.Remove(); err != nil {
		return err
	}
	return ic.Install(db)
}

// ---------------------------------------------------------------------------
// internal helpers
// ---------------------------------------------------------------------------

// generate dispatches to the appropriate per-tool generator.
func (ic *Interceptor) generate(tool string, entries []kb.KBEntry) string {
	switch tool {
	case "hyprland":
		return generateHyprland(entries, ic.fifoPath)
	case "tmux":
		return generateTmux(entries, ic.fifoPath)
	case "kitty":
		return generateKitty(entries, ic.fifoPath)
	case "qutebrowser":
		return generateQutebrowser(entries, ic.fifoPath)
	case "yazi":
		return generateYazi(entries, ic.fifoPath)
	default:
		return ""
	}
}

// writeFileWithDirs creates all parent directories then atomically writes
// content to path (mode 0644).
func writeFileWithDirs(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	return os.WriteFile(path, []byte(content), 0644)
}
