package coach

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/shaiknoorullah/wtfrc/internal/kb"
)

// ---------------------------------------------------------------------------
// TestGenerateHyprland
// ---------------------------------------------------------------------------

func TestGenerateHyprland(t *testing.T) {
	fifoPath := "/run/user/1000/wtfrc/coach.fifo"
	entries := []kb.KBEntry{
		{RawBinding: strPtr("$mod, j"), RawAction: strPtr("movefocus, l")},
		{RawBinding: strPtr("$mod, q"), RawAction: strPtr("killactive")},
	}

	out := generateHyprland(entries, fifoPath)

	checks := []struct {
		desc string
		want string
	}{
		{"comment header", "# Auto-generated by wtfrc coach"},
		{"first echo", `echo "kb:hyprland:movefocus, l"`},
		{"first dispatch", `hyprctl dispatch movefocus, l`},
		{"second echo", `echo "kb:hyprland:killactive"`},
		{"second dispatch", `hyprctl dispatch killactive`},
		{"fifo path present", fifoPath},
		{"bind keyword", "bind = "},
	}

	for _, c := range checks {
		t.Run(c.desc, func(t *testing.T) {
			if !strings.Contains(out, c.want) {
				t.Errorf("generateHyprland output missing %q\noutput:\n%s", c.want, out)
			}
		})
	}

	// Both entries should be wrapped
	if count := strings.Count(out, "hyprctl dispatch"); count != 2 {
		t.Errorf("expected 2 hyprctl dispatch lines, got %d", count)
	}
}

func TestGenerateHyprlandSkipsNilFields(t *testing.T) {
	fifoPath := "/tmp/test.fifo"
	entries := []kb.KBEntry{
		{RawBinding: nil, RawAction: strPtr("movefocus, l")},   // nil binding — skip
		{RawBinding: strPtr("$mod, j"), RawAction: nil},        // nil action — skip
		{RawBinding: strPtr("$mod, k"), RawAction: strPtr("movefocus, u")}, // valid
	}

	out := generateHyprland(entries, fifoPath)

	if count := strings.Count(out, "hyprctl dispatch"); count != 1 {
		t.Errorf("expected 1 hyprctl dispatch line (nil entries skipped), got %d\noutput:\n%s", count, out)
	}
}

// ---------------------------------------------------------------------------
// TestGenerateTmux
// ---------------------------------------------------------------------------

func TestGenerateTmux(t *testing.T) {
	fifoPath := "/run/user/1000/wtfrc/coach.fifo"
	entries := []kb.KBEntry{
		{RawBinding: strPtr("bind-key -T prefix o"), RawAction: strPtr("select-pane -t :.+")},
	}

	out := generateTmux(entries, fifoPath)

	checks := []struct {
		desc string
		want string
	}{
		{"comment header", "# Auto-generated by wtfrc coach"},
		{"run-shell present", "run-shell"},
		{"semicolon separator", `\;`},
		{"echo kb:tmux prefix", "kb:tmux:"},
		{"fifo path present", fifoPath},
		{"original action present", "select-pane -t :.+"},
	}

	for _, c := range checks {
		t.Run(c.desc, func(t *testing.T) {
			if !strings.Contains(out, c.want) {
				t.Errorf("generateTmux output missing %q\noutput:\n%s", c.want, out)
			}
		})
	}
}

func TestGenerateTmuxSkipsNilFields(t *testing.T) {
	fifoPath := "/tmp/test.fifo"
	entries := []kb.KBEntry{
		{RawBinding: nil, RawAction: strPtr("select-pane -t :.+")},
		{RawBinding: strPtr("bind-key -T prefix p"), RawAction: nil},
		{RawBinding: strPtr("bind-key -T prefix o"), RawAction: strPtr("select-pane -t :.+")},
	}

	out := generateTmux(entries, fifoPath)

	if count := strings.Count(out, "run-shell"); count != 1 {
		t.Errorf("expected 1 run-shell line, got %d\noutput:\n%s", count, out)
	}
}

// ---------------------------------------------------------------------------
// TestGenerateKitty
// ---------------------------------------------------------------------------

func TestGenerateKitty(t *testing.T) {
	fifoPath := "/run/user/1000/wtfrc/coach.fifo"
	entries := []kb.KBEntry{
		{RawBinding: strPtr("ctrl+shift+t"), RawAction: strPtr("new_tab")},
	}

	out := generateKitty(entries, fifoPath)

	checks := []struct {
		desc string
		want string
	}{
		{"comment header", "# Auto-generated by wtfrc coach"},
		{"combine keyword", "combine"},
		{"launch background", "launch --type=background"},
		{"echo kb:kitty prefix", "kb:kitty:"},
		{"fifo path present", fifoPath},
		{"original binding", "ctrl+shift+t"},
		{"original action", "new_tab"},
		{"map keyword", "map "},
	}

	for _, c := range checks {
		t.Run(c.desc, func(t *testing.T) {
			if !strings.Contains(out, c.want) {
				t.Errorf("generateKitty output missing %q\noutput:\n%s", c.want, out)
			}
		})
	}
}

func TestGenerateKittySkipsNilFields(t *testing.T) {
	fifoPath := "/tmp/test.fifo"
	entries := []kb.KBEntry{
		{RawBinding: nil, RawAction: strPtr("new_tab")},
		{RawBinding: strPtr("ctrl+shift+t"), RawAction: nil},
		{RawBinding: strPtr("ctrl+shift+w"), RawAction: strPtr("close_tab")},
	}

	out := generateKitty(entries, fifoPath)

	if count := strings.Count(out, "combine"); count != 1 {
		t.Errorf("expected 1 combine line, got %d\noutput:\n%s", count, out)
	}
}

// ---------------------------------------------------------------------------
// TestGenerateQutebrowser
// ---------------------------------------------------------------------------

func TestGenerateQutebrowser(t *testing.T) {
	fifoPath := "/run/user/1000/wtfrc/coach.fifo"
	entries := []kb.KBEntry{
		{RawBinding: strPtr("f"), RawAction: strPtr("hint")},
	}

	out := generateQutebrowser(entries, fifoPath)

	checks := []struct {
		desc string
		want string
	}{
		{"comment header", "# Auto-generated by wtfrc coach"},
		{"python import os", "import os"},
		{"spawn -d", "spawn -d"},
		{"double semicolon", ";;"},
		{"echo kb:qb prefix", "kb:qb:"},
		{"fifo path present", fifoPath},
		{"original binding", "'f'"},
		{"original action", "hint"},
		{"config.bind", "config.bind"},
	}

	for _, c := range checks {
		t.Run(c.desc, func(t *testing.T) {
			if !strings.Contains(out, c.want) {
				t.Errorf("generateQutebrowser output missing %q\noutput:\n%s", c.want, out)
			}
		})
	}
}

func TestGenerateQutebrowserSkipsNilFields(t *testing.T) {
	fifoPath := "/tmp/test.fifo"
	entries := []kb.KBEntry{
		{RawBinding: nil, RawAction: strPtr("hint")},
		{RawBinding: strPtr("f"), RawAction: nil},
		{RawBinding: strPtr("o"), RawAction: strPtr("open")},
	}

	out := generateQutebrowser(entries, fifoPath)

	if count := strings.Count(out, "spawn -d"); count != 1 {
		t.Errorf("expected 1 spawn -d line, got %d\noutput:\n%s", count, out)
	}
}

// ---------------------------------------------------------------------------
// TestGenerateYazi
// ---------------------------------------------------------------------------

func TestGenerateYazi(t *testing.T) {
	fifoPath := "/run/user/1000/wtfrc/coach.fifo"
	entries := []kb.KBEntry{
		{RawBinding: strPtr("j"), RawAction: strPtr("arrow 1")},
	}

	out := generateYazi(entries, fifoPath)

	checks := []struct {
		desc string
		want string
	}{
		{"comment header", "# Auto-generated by wtfrc coach"},
		{"manager prepend_keymap", "[[manager.prepend_keymap]]"},
		{"shell keyword", "shell"},
		{"echo kb:yazi prefix", "kb:yazi:"},
		{"fifo path present", fifoPath},
		{"original binding", `"j"`},
		{"original action", "arrow 1"},
		{"on key", `on = [`},
		{"run key", `run = [`},
	}

	for _, c := range checks {
		t.Run(c.desc, func(t *testing.T) {
			if !strings.Contains(out, c.want) {
				t.Errorf("generateYazi output missing %q\noutput:\n%s", c.want, out)
			}
		})
	}
}

func TestGenerateYaziSkipsNilFields(t *testing.T) {
	fifoPath := "/tmp/test.fifo"
	entries := []kb.KBEntry{
		{RawBinding: nil, RawAction: strPtr("arrow 1")},
		{RawBinding: strPtr("j"), RawAction: nil},
		{RawBinding: strPtr("k"), RawAction: strPtr("arrow -1")},
	}

	out := generateYazi(entries, fifoPath)

	if count := strings.Count(out, "[[manager.prepend_keymap]]"); count != 1 {
		t.Errorf("expected 1 [[manager.prepend_keymap]] section, got %d\noutput:\n%s", count, out)
	}
}

// ---------------------------------------------------------------------------
// TestInstallRemove
// ---------------------------------------------------------------------------

func TestInstallRemove(t *testing.T) {
	tmpDir := t.TempDir()
	fifoPath := filepath.Join(tmpDir, "coach.fifo")

	ic := NewInterceptor(fifoPath)

	// Override all config paths to use temp dir subdirectories.
	toolPaths := map[string]string{
		"hyprland":    filepath.Join(tmpDir, "hypr", "wtfrc-intercept.conf"),
		"tmux":        filepath.Join(tmpDir, "tmux", "wtfrc-intercept.conf"),
		"kitty":       filepath.Join(tmpDir, "kitty", "wtfrc-intercept.conf"),
		"qutebrowser": filepath.Join(tmpDir, "qutebrowser", "wtfrc-intercept.py"),
		"yazi":        filepath.Join(tmpDir, "yazi", "wtfrc-intercept.toml"),
	}
	for tool, path := range toolPaths {
		ic.SetConfigPath(tool, path)
	}

	// Open a real DB (in-memory for testing).
	dbPath := filepath.Join(tmpDir, "test.db")
	db, err := kb.Open(dbPath)
	if err != nil {
		t.Fatalf("kb.Open: %v", err)
	}
	defer db.Close()

	// Insert test entries.
	binding := "$mod, j"
	action := "movefocus, l"
	_, err = db.InsertEntry(&kb.KBEntry{
		Tool:       "hyprland",
		Type:       "keybind",
		RawBinding: &binding,
		RawAction:  &action,
		SourceFile: "test.conf",
		FileHash:   "abc",
	}, nil)
	if err != nil {
		t.Fatalf("InsertEntry: %v", err)
	}

	tmuxBinding := "bind-key -T prefix o"
	tmuxAction := "select-pane -t :.+"
	_, err = db.InsertEntry(&kb.KBEntry{
		Tool:       "tmux",
		Type:       "keybind",
		RawBinding: &tmuxBinding,
		RawAction:  &tmuxAction,
		SourceFile: "test.conf",
		FileHash:   "def",
	}, nil)
	if err != nil {
		t.Fatalf("InsertEntry: %v", err)
	}

	// Install — should create files at the overridden paths.
	if err := ic.Install(db); err != nil {
		t.Fatalf("Install: %v", err)
	}

	// Verify files were created.
	for tool, path := range toolPaths {
		info, err := os.Stat(path)
		if err != nil {
			t.Errorf("tool %s: file not created at %s: %v", tool, path, err)
			continue
		}
		_ = info

		content, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("tool %s: read file: %v", tool, err)
			continue
		}

		switch tool {
		case "hyprland":
			if !strings.Contains(string(content), "hyprctl dispatch") {
				t.Errorf("hyprland config missing hyprctl dispatch\ncontent:\n%s", content)
			}
		case "tmux":
			if !strings.Contains(string(content), "run-shell") {
				t.Errorf("tmux config missing run-shell\ncontent:\n%s", content)
			}
		case "kitty", "qutebrowser", "yazi":
			// These tools have no entries inserted; they should be empty files.
			if len(content) != 0 {
				t.Errorf("tool %s: expected empty file (no entries), got %d bytes", tool, len(content))
			}
		}
	}

	// Remove — all files should become empty.
	if err := ic.Remove(); err != nil {
		t.Fatalf("Remove: %v", err)
	}

	for tool, path := range toolPaths {
		content, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("tool %s: read after Remove: %v", tool, err)
			continue
		}
		if len(content) != 0 {
			t.Errorf("tool %s: expected empty file after Remove, got %d bytes", tool, len(content))
		}
	}
}

func TestRegenerate(t *testing.T) {
	tmpDir := t.TempDir()
	fifoPath := filepath.Join(tmpDir, "coach.fifo")

	ic := NewInterceptor(fifoPath)

	toolPaths := map[string]string{
		"hyprland":    filepath.Join(tmpDir, "hypr", "wtfrc-intercept.conf"),
		"tmux":        filepath.Join(tmpDir, "tmux", "wtfrc-intercept.conf"),
		"kitty":       filepath.Join(tmpDir, "kitty", "wtfrc-intercept.conf"),
		"qutebrowser": filepath.Join(tmpDir, "qutebrowser", "wtfrc-intercept.py"),
		"yazi":        filepath.Join(tmpDir, "yazi", "wtfrc-intercept.toml"),
	}
	for tool, path := range toolPaths {
		ic.SetConfigPath(tool, path)
	}

	dbPath := filepath.Join(tmpDir, "test.db")
	db, err := kb.Open(dbPath)
	if err != nil {
		t.Fatalf("kb.Open: %v", err)
	}
	defer db.Close()

	binding := "$mod, j"
	action := "movefocus, l"
	_, err = db.InsertEntry(&kb.KBEntry{
		Tool:       "hyprland",
		Type:       "keybind",
		RawBinding: &binding,
		RawAction:  &action,
		SourceFile: "test.conf",
		FileHash:   "abc",
	}, nil)
	if err != nil {
		t.Fatalf("InsertEntry: %v", err)
	}

	// Regenerate = Remove then Install.
	if err := ic.Regenerate(db); err != nil {
		t.Fatalf("Regenerate: %v", err)
	}

	hyprPath := toolPaths["hyprland"]
	content, err := os.ReadFile(hyprPath)
	if err != nil {
		t.Fatalf("read hyprland config: %v", err)
	}
	if !strings.Contains(string(content), "hyprctl dispatch") {
		t.Errorf("hyprland config missing hyprctl dispatch after Regenerate\ncontent:\n%s", content)
	}
}

func TestNewInterceptorPaths(t *testing.T) {
	ic := NewInterceptor("/tmp/test.fifo")

	tools := []string{"hyprland", "tmux", "kitty", "qutebrowser", "yazi"}
	for _, tool := range tools {
		path, ok := ic.configs[tool]
		if !ok {
			t.Errorf("tool %q not found in configs map", tool)
			continue
		}
		if path == "" {
			t.Errorf("tool %q has empty config path", tool)
		}
		if strings.HasPrefix(path, "~") {
			t.Errorf("tool %q path not expanded (starts with ~): %s", tool, path)
		}
	}
}
